"""Reviews for the new (iteration-3) products. Target 75-88% positive."""

NEW_REVIEWS = {
    # Xiaomi 14 Ultra — target ~82% positive
    "xiaomi-14-ultra": [
        ("The Leica cameras are legit — photos rival my dedicated camera in daylight.", "positive", "photography"),
        ("On-device AI Erase actually works — cleaner than most cloud tools I've used.", "positive", "content_creation"),
        ("Battery + 90W charging combo is a game-changer — never worry about power.", "positive", "professional"),
        ("HyperOS 2 has some rough edges — occasional stutter on animations.", "negative", "family_general"),
        ("AI Interpreter saved me on my Japan trip — real-time and accurate.", "positive", "family_general"),
        ("Gaming performance is smooth for casual games; runs warm on demanding titles.", "negative", "gaming"),
        ("Camera zoom for wildlife photography is stunning.", "positive", "photography"),
        ("The 1-inch sensor low-light performance is unreal.", "positive", "photography"),
        ("A bit heavy for daily carry — the camera bump is noticeable in pocket.", "negative", "family_general"),
        ("AI ProCut video mode saved me hours in editing my travel vlogs.", "positive", "content_creation"),
        ("Solid all-rounder — great for a photography-heavy family.", "positive", "family_general"),
        ("MIUI/HyperOS ads in system apps remain a real annoyance.", "negative", "family_general"),
        ("Fast charging is genuinely magic — 30 mins for a full day.", "positive", "professional"),
        ("The variable aperture actually makes a visible difference in portraits.", "positive", "photography"),
        ("Excellent phone for content creators on a budget vs. flagship rivals.", "positive", "content_creation"),
        ("Screen is beautiful but the software feels less polished than Samsung.", "negative", "professional"),
        ("Camera in low-light indoor conditions is genuinely impressive.", "positive", "photography"),
    ],
    # Dell XPS 14 AI — target ~78% positive
    "dell-xps-14-ai": [
        ("Battery life on this ARM XPS is next level — 20 hours easily on real work.", "positive", "professional"),
        ("Copilot+ Recall is actually useful when you get past privacy setup.", "positive", "professional"),
        ("Some x86 apps still have compatibility hiccups on Windows-on-ARM.", "negative", "professional"),
        ("OLED display is spectacular for photo editing.", "positive", "photography"),
        ("Snapdragon X handles heavy multitasking with minimal fan noise.", "positive", "professional"),
        ("Zero-lattice keyboard is polarising — took a while to get used to.", "negative", "professional"),
        ("The haptic touchpad is amazing for Lightroom slider work.", "positive", "photography"),
        ("Not the best for heavy gaming — but casual games run fine.", "negative", "gaming"),
        ("Great for coding compilation with the NPU handling background AI.", "positive", "student"),
        ("Local Copilot features run without cloud latency — private and fast.", "positive", "professional"),
        ("OLED sometimes gets reflective in bright office lighting.", "negative", "professional"),
        ("Snappy for research, docs, and browser tabs — perfect for uni.", "positive", "student"),
        ("Bought for a home-work parent — quiet, cool, and light.", "positive", "family_general"),
        ("Speakers are OK but not the best on a premium laptop.", "negative", "content_creation"),
        ("Video calls and Studio Effects are noticeably better than my last laptop.", "positive", "professional"),
        ("Fantastic laptop for photo culling and edits on travel days.", "positive", "photography"),
        ("Price is aggressive vs. equivalent MacBook Pro — good value.", "positive", "professional"),
    ],
    # Sony Bravia 8 AI — target ~88% positive
    "sony-bravia-8-ai": [
        ("Picture quality is reference-grade — best OLED I've owned.", "positive", "family_general"),
        ("QD-OLED colors pop in a way regular OLED just doesn't.", "positive", "content_creation"),
        ("Acoustic Surface Audio is genuinely different — sound comes from the screen.", "positive", "family_general"),
        ("Menu system is dense — took a while to learn the settings.", "negative", "family_general"),
        ("PS5 Perfect Gaming Mode is set-and-forget — no fiddling.", "positive", "gaming"),
        ("XR AI Processor keeps details visible even in fast action scenes.", "positive", "family_general"),
        ("Live sports and cricket look incredible with cognitive processing.", "positive", "family_general"),
        ("Voice search on Google TV is fast and accurate.", "positive", "family_general"),
        ("Very high price — feels premium but not everyone will justify it.", "negative", "family_general"),
        ("Movies feel like a small home theatre — dialogue clarity is amazing.", "positive", "family_general"),
        ("Reviewing my photos on this feels like a color-accurate monitor.", "positive", "photography"),
        ("Fantastic for premium film watching — Dolby Vision handled beautifully.", "positive", "content_creation"),
        ("Documentary and educational content looks super immersive for the kids.", "positive", "student"),
        ("HDMI 2.1 ports fewer than competition — planning around it is annoying.", "negative", "gaming"),
        ("Workout videos and streams look sharp on the big OLED.", "positive", "fitness_health"),
        ("Even old SD content is upscaled better than any TV I've had before.", "positive", "family_general"),
        ("Kids adore how vivid animations look — noticeable upgrade for family time.", "positive", "family_general"),
    ],
    # LG C4 OLED AI TV — target ~86% positive
    "lg-c4-oled-ai-tv": [
        ("144Hz OLED is unbeatable for PS5 gaming — buttery smooth Dolby Vision.", "positive", "gaming"),
        ("Alpha 9 Gen 7 processor upscales lower-res content beautifully.", "positive", "family_general"),
        ("webOS 24 AI chatbot answers TV questions surprisingly well.", "positive", "family_general"),
        ("Slight bug where HDMI-CEC sometimes drops the input — annoying.", "negative", "family_general"),
        ("Great mid-premium OLED — better value than the Sony flagship.", "positive", "family_general"),
        ("Sound Pro 11.1.2 upmixing sounds much richer than the panel deserves.", "positive", "family_general"),
        ("Dolby Vision gaming at 144Hz is a competitive-grade experience.", "positive", "gaming"),
        ("Remote is fine but not as premium-feeling as expected at this price.", "negative", "family_general"),
        ("Auto-genre detection swaps modes seamlessly — no menu diving.", "positive", "family_general"),
        ("Family movie nights feel cinema-quality — everyone approves.", "positive", "family_general"),
        ("Kids' cartoons look vivid and animated content stays vivid.", "positive", "family_general"),
        ("Wall mounting is tricky — panel is thin but wide.", "negative", "home_management"),
        ("Genre detection sometimes miscategorises music videos.", "negative", "family_general"),
        ("Streaming apps run smooth and interface is snappier than older LG TVs.", "positive", "family_general"),
        ("Photography portfolio slideshows look gorgeous.", "positive", "photography"),
        ("Educational content for kids looks vivid — makes learning fun.", "positive", "student"),
        ("Perfect for a movie-focused family that wants premium at value price.", "positive", "family_general"),
    ],
    # Samsung Galaxy Watch 8 — target ~80% positive
    "samsung-galaxy-watch-8": [
        ("Rotating bezel is back and it's a joy to use — best watch input.", "positive", "family_general"),
        ("Galaxy AI Wellness Coach nudges are actually helpful, not annoying.", "positive", "fitness_health"),
        ("BP monitoring requires monthly cuff calibration — a bit inconvenient.", "negative", "fitness_health"),
        ("3-day battery life with AOD is a big step up from previous generations.", "positive", "family_general"),
        ("Sleep coaching insights are surprisingly detailed and actionable.", "positive", "fitness_health"),
        ("Some apps still slow to load compared to my old Apple Watch.", "negative", "family_general"),
        ("Comfortable for daily wear — the rotating bezel is a genuine highlight.", "positive", "family_general"),
        ("Health features work well as a general wellness companion.", "positive", "family_general"),
        ("BP readings are useful for tracking patterns — not a replacement for the doctor.", "positive", "fitness_health"),
        ("Great for busy office workers — good stress and move reminders.", "positive", "professional"),
        ("Notifications are smart and don't overwhelm during meetings.", "positive", "professional"),
        ("Battery drop is faster during workouts with GPS + music.", "negative", "fitness_health"),
        ("Kids love the vivid AMOLED and playful watch faces.", "positive", "family_general"),
        ("Design feels more premium than my last Watch — solid build.", "positive", "family_general"),
        ("Water tracking works well through the day.", "positive", "fitness_health"),
        ("Some AI features feel gimmicky and I stopped using them after a week.", "negative", "family_general"),
        ("Fitness tracking during running and cycling is accurate.", "positive", "fitness_health"),
    ],
    # Garmin Venu 4 AI — target ~87% positive
    "garmin-venu-4-ai": [
        ("Battery life is unbelievable — 10 days easily with real use.", "positive", "fitness_health"),
        ("Garmin AI Coach genuinely adapted to my running plan over weeks.", "positive", "fitness_health"),
        ("Elevate 5 sensor is noticeably more accurate than the older Venu.", "positive", "fitness_health"),
        ("Interface is a bit dated compared to Apple/Samsung watches.", "negative", "family_general"),
        ("Morning Report has become my must-read every day.", "positive", "professional"),
        ("Auto workout detection reliably picks up walks, runs, and cycling.", "positive", "fitness_health"),
        ("Body Battery score is way more useful than I expected.", "positive", "fitness_health"),
        ("Music storage on-watch means I run without a phone.", "positive", "fitness_health"),
        ("Notifications are limited compared to Apple/Samsung ecosystem.", "negative", "professional"),
        ("Rock-solid GPS tracking — perfect for marathon training.", "positive", "fitness_health"),
        ("Stress and HRV data helps me schedule harder training days.", "positive", "fitness_health"),
        ("Perfect for a fitness-focused user; less good for casual social features.", "positive", "fitness_health"),
        ("Sleep tracking is more nuanced than any smartwatch I've used.", "positive", "fitness_health"),
        ("Great watch for busy parents balancing family and fitness.", "positive", "family_general"),
        ("Would love better voice control — falls behind here.", "negative", "family_general"),
        ("SpO2 and skin temp readings feel genuinely useful.", "positive", "fitness_health"),
        ("Simple to sync with family fitness accounts.", "positive", "family_general"),
    ],
    # XREAL One Pro AI — target ~76% positive
    "xreal-one-pro-ai": [
        ("Watching films on a virtual 200-inch screen on flights is amazing.", "positive", "family_general"),
        ("Multi-monitor productivity on flights is genuinely useful.", "positive", "professional"),
        ("Front dark tint could be adjustable — occasionally too dark indoors.", "negative", "family_general"),
        ("Gaming on Steam Deck via USB-C is a killer feature.", "positive", "gaming"),
        ("X1 spatial chip makes pinned windows stay put — no drift.", "positive", "professional"),
        ("Prescription insert setup was more complex than the marketing suggests.", "negative", "family_general"),
        ("Genuinely lightweight — I forget I'm wearing them for a while.", "positive", "family_general"),
        ("AI assistant vision is fun but occasionally misses context.", "negative", "professional"),
        ("Perfect for photographers editing on the go with a big virtual monitor.", "positive", "photography"),
        ("Kids love watching family photos and videos on the huge virtual screen.", "positive", "family_general"),
        ("Battery life via phone is limited — carrying a power bank is essential.", "negative", "content_creation"),
        ("Content creators — these are a portable second monitor everywhere.", "positive", "content_creation"),
        ("Some competitive games have too much motion for comfortable AR play.", "negative", "gaming"),
        ("Study sessions on planes with a virtual monitor are surprisingly productive.", "positive", "student"),
        ("Recipe pinning in the kitchen while cooking is oddly delightful.", "positive", "home_management"),
        ("Comfort for the first hour is great; extended wear can feel warm.", "negative", "family_general"),
        ("Best for people who travel a lot and want a private big screen.", "positive", "professional"),
    ],
    # Samsung Bespoke AI Steam Oven — target ~82% positive
    "samsung-bespoke-ai-oven": [
        ("The interior camera + AI recognition is more useful than I expected.", "positive", "home_management"),
        ("Steam + convection genuinely gives restaurant-quality bread and roasts.", "positive", "family_general"),
        ("SmartThings recipe sync is slick — one-tap oven programs.", "positive", "family_general"),
        ("App integration is occasionally buggy — sometimes fails to sync.", "negative", "home_management"),
        ("Family Sunday roasts are consistently perfect since I got it.", "positive", "family_general"),
        ("Preheat learning based on usage patterns is a real time-saver.", "positive", "home_management"),
        ("Setup and wifi pairing was frustrating — took multiple tries.", "negative", "home_management"),
        ("Meal prep chicken and salmon come out with restaurant texture.", "positive", "fitness_health"),
        ("Auto-off gave me peace of mind with kids in the house.", "positive", "family_general"),
        ("AI recipes lean towards Western cuisine — Indian recipe suggestions are limited.", "negative", "family_general"),
        ("Energy bills dropped for our heavy cooking family.", "positive", "home_management"),
        ("Cooking-content shoots are so much easier with the camera stream.", "positive", "content_creation"),
        ("Bread baking is genuinely bakery-quality with the steam function.", "positive", "family_general"),
        ("Learning curve for advanced modes is steep.", "negative", "home_management"),
        ("Restaurant-quality food at home — worth every rupee.", "positive", "family_general"),
        ("Family meal-prep Sundays are so much faster and easier.", "positive", "home_management"),
        ("Compact enough for smaller Indian kitchens but powerful.", "positive", "home_management"),
    ],
}


def merge_into_reviews(existing):
    combined = dict(existing)
    combined.update(NEW_REVIEWS)
    return combined
